name: Run Tests on Pull Requests

# Trigger the workflow on pull requests
on:
  pull_request:
    branches:
      - main # Replace with your target branch if different

# Define the jobs to run
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16 # Specify the Node.js version

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run tests
      - name: Run tests
        run: npm test

